### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [VulnTotal-Team/yarb#20]
Traceback (most recent call last):
  File "/home/runner/work/yarb/yarb/yarb.py", line 242, in <module>
    asyncio.run(main())
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/work/yarb/yarb/yarb.py", line 239, in main
    await job(args)
  File "/home/runner/work/yarb/yarb/yarb.py", line 218, in job
    await bot.send(bot.parse_results(results))
TypeError: object NoneType can't be used in 'await' expression
Error: Process completed with exit code 1.

**Comment by firmianay** [comment]
用的哪个推送？

**Comment by adminlove520** [comment]
企业微信
然后同时启用dingding&wecom 钉钉不推送

**Comment by adminlove520** [comment]
单独启用企业微信也会报这个错   我记得之前好像是正常的

**Comment by adminlove520** [comment]
GITHUB的actions方式

**Comment by firmianay** [comment]
师傅再试试
